export const API_ROUTES = {
  auth: '/api/auth',
  config: '/api/config',
  issuerProfile: '/api/issuer-profile',
  clients: '/api/clients',
  client: (id: string) => `/api/clients/${id}`,
  catalogue: '/api/catalogue',
  catalogueItem: (id: string) => `/api/catalogue/${id}`,
  documents: '/api/documents',
  document: (id: string) => `/api/documents/${id}`,
  documentIssue: (id: string) => `/api/documents/${id}/issue`,
  documentCancel: (id: string) => `/api/documents/${id}/cancel`,
  documentMarkPaid: (id: string) => `/api/documents/${id}/paid`,
  documentRender: (id: string) => `/api/documents/${id}/render`,
  documentEmail: (id: string) => `/api/documents/${id}/email`,
  series: '/api/series',
  subscription: '/api/billing/subscription',
  checkout: '/api/billing/checkout',
  paddleWebhook: '/api/billing/webhook',
} as const;
