import type { DocumentDto } from '@fakturcho/shared-types';

export const bgDomesticStandardInvoice: DocumentDto = {
  id: 'doc-bg-domestic-1',
  documentType: 'invoice',
  status: 'sent',
  number: 42,
  numberPrefix: null,
  numberSuffix: null,
  referenceNumber: null,
  originalDocumentId: null,
  issuedAt: '2026-09-01',
  taxEventAt: '2026-09-01',
  dueAt: '2026-09-15',
  validUntil: null,
  deliveryDate: '2026-09-01',
  buyerReference: 'PO-2026-118',
  paymentMeansCode: '30',
  paymentTermsNote: '14 дни от датата на издаване',
  subtotal: 100000,
  discountTotal: 0,
  amount: 120000,
  vatIncluded: false,
  vatRateBp: 2000,
  vatAmount: 20000,
  vatExemptionGround: null,
  currency: 'EUR',
  clientId: 'client-1',
  preparedBy: 'Иван Иванов',
  notes: null,
  emailText: null,
  emailedAt: null,
  templateId: 'classic',
  documentLanguage: 'bg',
  issuer: {
    companyName: 'Тестова Компания ЕООД',
    eik: '123456789',
    mol: 'Мария Петрова',
    addressLine: 'ул. Витоша 15, гр. София',
    street: 'ул. Витоша 15',
    postcode: '1000',
    countyRegion: null,
    city: 'София',
    country: 'BG',
    phone: '+359 888 123 456',
    vatRegistered: true,
    vatNumber: 'BG123456789',
    bankName: 'Банка ДСК АД',
    iban: 'BG80BNBG96611020345678',
    bic: 'BNBGBGSD',
    altIban: null,
    identifiers: {},
  },
  recipient: {
    companyName: 'Клиентска Фирма ООД',
    eik: '987654321',
    vatNumber: 'BG987654321',
    address: 'бул. Свобода 5, гр. Пловдив',
    street: 'бул. Свобода 5',
    postcode: '4000',
    countyRegion: null,
    country: 'BG',
    email: 'office@client.bg',
    mol: 'Петър Георгиев',
    sdiRecipientCode: null,
    pec: null,
  },
  lineItems: [
    {
      id: 'line-1',
      name: 'Консултантска услуга',
      quantity: '10',
      unitPrice: 10000,
      lineTotal: 100000,
      sortOrder: 0,
      vatRateBp: 2000,
      vatCategory: 'S',
      unitCode: 'HUR',
    },
  ],
  discounts: [],
  createdAt: '2026-09-01T09:00:00.000Z',
  updatedAt: '2026-09-01T09:00:00.000Z',
};
