import type { DocumentDto } from '@fakturcho/shared-types';

export const deDomesticStandardInvoice: DocumentDto = {
  id: 'doc-de-domestic-1',
  documentType: 'invoice',
  status: 'sent',
  number: 7,
  numberPrefix: null,
  numberSuffix: null,
  referenceNumber: null,
  originalDocumentId: null,
  issuedAt: '2026-09-03',
  taxEventAt: '2026-09-03',
  dueAt: '2026-09-17',
  validUntil: null,
  deliveryDate: '2026-09-03',
  buyerReference: 'BESTELLUNG-55',
  paymentMeansCode: '30',
  paymentTermsNote: 'Zahlbar innerhalb von 14 Tagen',
  subtotal: 500000,
  discountTotal: 0,
  amount: 595000,
  vatIncluded: false,
  vatRateBp: 1900,
  vatAmount: 95000,
  vatExemptionGround: null,
  currency: 'EUR',
  clientId: 'client-3',
  preparedBy: 'Anna Schmidt',
  notes: null,
  emailText: null,
  emailedAt: null,
  templateId: 'classic',
  documentLanguage: 'en',
  issuer: {
    companyName: 'Muster Consulting GmbH',
    eik: 'HRB 123456',
    mol: null,
    addressLine: 'Musterstraße 10, 10115 Berlin',
    street: 'Musterstraße 10',
    postcode: '10115',
    countyRegion: null,
    city: 'Berlin',
    country: 'DE',
    phone: '+49 30 1234567',
    vatRegistered: true,
    vatNumber: 'DE123456789',
    bankName: 'Deutsche Bank AG',
    iban: 'DE89370400440532013000',
    bic: 'COBADEFFXXX',
    altIban: null,
    identifiers: {},
  },
  recipient: {
    companyName: 'Beispiel AG',
    eik: 'HRB 654321',
    vatNumber: 'DE987654321',
    address: 'Beispielweg 3, 80331 München',
    street: 'Beispielweg 3',
    postcode: '80331',
    countyRegion: null,
    city: 'München',
    country: 'DE',
    email: 'buchhaltung@beispiel.de',
    mol: null,
    sdiRecipientCode: null,
    pec: null,
  },
  lineItems: [
    {
      id: 'line-1',
      name: 'Management consulting services',
      quantity: '20',
      unitPrice: 25000,
      lineTotal: 500000,
      sortOrder: 0,
      vatRateBp: 1900,
      vatCategory: 'S',
      unitCode: 'HUR',
    },
  ],
  discounts: [],
  createdAt: '2026-09-03T09:00:00.000Z',
  updatedAt: '2026-09-03T09:00:00.000Z',
};
