import type { DocumentDto } from '@fakturcho/shared-types';

export const bgToEuReverseChargeInvoice: DocumentDto = {
  id: 'doc-eu-reverse-charge-1',
  documentType: 'invoice',
  status: 'sent',
  number: 43,
  numberPrefix: null,
  numberSuffix: null,
  referenceNumber: null,
  originalDocumentId: null,
  issuedAt: '2026-09-02',
  taxEventAt: '2026-09-02',
  dueAt: '2026-09-16',
  validUntil: null,
  deliveryDate: '2026-09-02',
  buyerReference: 'DE-ORDER-77',
  paymentMeansCode: '58',
  paymentTermsNote: '14 дни от датата на издаване',
  transportReason: null,
  transportedAt: null,
  carrierName: null,
  transportNote: null,
  correctionReason: null,
  subtotal: 200000,
  discountTotal: 0,
  amount: 200000,
  vatIncluded: false,
  vatRateBp: 0,
  vatAmount: 0,
  vatExemptionGround: 'Обратно начисляване – чл. 21, ал. 2 от ЗДДС',
  currency: 'EUR',
  clientId: 'client-2',
  preparedBy: 'Иван Иванов',
  notes: null,
  emailText: null,
  emailedAt: null,
  templateId: 'classic',
  documentLanguage: 'bg',
  issuer: {
    companyName: 'Тестова Компания ЕООД',
    eik: '123456789',
    mol: 'Мария Петрова',
    addressLine: 'ул. Витоша 15, гр. София',
    street: 'ул. Витоша 15',
    postcode: '1000',
    countyRegion: null,
    city: 'София',
    country: 'BG',
    phone: '+359 888 123 456',
    vatRegistered: true,
    vatNumber: 'BG123456789',
    bankName: 'Банка ДСК АД',
    iban: 'BG80BNBG96611020345678',
    bic: 'BNBGBGSD',
    altIban: null,
    identifiers: {},
  },
  recipient: {
    companyName: 'Muster GmbH',
    eik: null,
    vatNumber: 'DE123456789',
    address: 'Musterstraße 10, 10115 Berlin',
    street: 'Musterstraße 10',
    postcode: '10115',
    countyRegion: null,
    city: 'Berlin',
    country: 'DE',
    email: 'buchhaltung@muster.de',
    mol: null,
    sdiRecipientCode: null,
    pec: null,
  },
  lineItems: [
    {
      id: 'line-1',
      name: 'Software development services',
      quantity: '40',
      unitPrice: 5000,
      lineTotal: 200000,
      sortOrder: 0,
      vatRateBp: 0,
      vatCategory: 'AE',
      unitCode: 'HUR',
    },
  ],
  discounts: [],
  createdAt: '2026-09-02T09:00:00.000Z',
  updatedAt: '2026-09-02T09:00:00.000Z',
};
