import type { DocumentDto } from '@fakturcho/shared-types';

export const roDomesticStandardInvoice: DocumentDto = {
  id: 'doc-ro-domestic-1',
  documentType: 'invoice',
  status: 'sent',
  number: 11,
  numberPrefix: null,
  numberSuffix: null,
  referenceNumber: null,
  originalDocumentId: null,
  issuedAt: '2026-09-05',
  taxEventAt: '2026-09-05',
  dueAt: '2026-09-19',
  validUntil: null,
  deliveryDate: '2026-09-05',
  buyerReference: 'ORDIN-2026-9',
  paymentMeansCode: '30',
  paymentTermsNote: 'Plată în 14 zile de la data emiterii',
  transportReason: null,
  transportedAt: null,
  carrierName: null,
  transportNote: null,
  subtotal: 100000,
  discountTotal: 0,
  amount: 119000,
  vatIncluded: false,
  vatRateBp: 1900,
  vatAmount: 19000,
  vatExemptionGround: null,
  currency: 'EUR',
  clientId: 'client-9',
  preparedBy: 'Andrei Popescu',
  notes: null,
  emailText: null,
  emailedAt: null,
  templateId: 'classic',
  documentLanguage: 'en',
  issuer: {
    companyName: 'Exemplu Consulting SRL',
    eik: '18547290',
    mol: null,
    addressLine: 'Str. Victoriei 10, București',
    street: 'Str. Victoriei 10',
    postcode: '010071',
    countyRegion: null,
    city: 'București',
    country: 'RO',
    phone: '+40 21 123 4567',
    vatRegistered: true,
    vatNumber: 'RO18547290',
    bankName: 'Banca Transilvania',
    iban: 'RO49AAAA1B31007593840000',
    bic: 'BTRLRO22',
    altIban: null,
    identifiers: {},
  },
  recipient: {
    companyName: 'Client Exemplu SA',
    eik: '14399840',
    vatNumber: 'RO14399840',
    address: 'Str. Republicii 5, Cluj-Napoca',
    street: 'Str. Republicii 5',
    postcode: '400015',
    countyRegion: null,
    city: 'Cluj-Napoca',
    country: 'RO',
    email: 'contabilitate@client-exemplu.ro',
    mol: null,
    sdiRecipientCode: null,
    pec: null,
  },
  lineItems: [
    {
      id: 'line-1',
      name: 'Servicii de consultanță',
      quantity: '10',
      unitPrice: 10000,
      lineTotal: 100000,
      sortOrder: 0,
      vatRateBp: 1900,
      vatCategory: 'S',
      unitCode: 'HUR',
    },
  ],
  discounts: [],
  createdAt: '2026-09-05T09:00:00.000Z',
  updatedAt: '2026-09-05T09:00:00.000Z',
};
