import type { DocumentDto } from '@fakturcho/shared-types';

export const esDomesticStandardInvoice: DocumentDto = {
  id: 'doc-es-domestic-1',
  documentType: 'invoice',
  status: 'sent',
  number: 15,
  numberPrefix: null,
  numberSuffix: null,
  referenceNumber: null,
  originalDocumentId: null,
  issuedAt: '2026-09-04',
  taxEventAt: '2026-09-04',
  dueAt: '2026-09-18',
  validUntil: null,
  deliveryDate: '2026-09-04',
  buyerReference: 'PEDIDO-2026-77',
  paymentMeansCode: '30',
  paymentTermsNote: 'Pago a 14 días desde la fecha de emisión',
  subtotal: 100000,
  discountTotal: 0,
  amount: 121000,
  vatIncluded: false,
  vatRateBp: 2100,
  vatAmount: 21000,
  vatExemptionGround: null,
  currency: 'EUR',
  clientId: 'client-4',
  preparedBy: 'Carlos Ruiz',
  notes: null,
  emailText: null,
  emailedAt: null,
  templateId: 'classic',
  documentLanguage: 'en',
  issuer: {
    companyName: 'Servicios Digitales Iberia S.L.',
    eik: 'B12345674',
    mol: null,
    addressLine: 'Calle Mayor 10, 28013 Madrid',
    street: 'Calle Mayor 10',
    postcode: '28013',
    countyRegion: null,
    city: 'Madrid',
    country: 'ES',
    phone: '+34 910 123 456',
    vatRegistered: true,
    vatNumber: 'ESB12345674',
    bankName: 'Banco Santander S.A.',
    iban: 'ES9121000418450200051332',
    bic: 'BSCHESMM',
    altIban: null,
    identifiers: {},
  },
  recipient: {
    companyName: 'Comercial Levante S.L.',
    eik: 'B00000018',
    vatNumber: 'ESB00000018',
    address: 'Valencia',
    street: 'Avenida del Puerto 22',
    postcode: '46023',
    countyRegion: null,
    country: 'ES',
    email: 'administracion@comerciallevante.es',
    mol: null,
    sdiRecipientCode: null,
    pec: null,
  },
  lineItems: [
    {
      id: 'line-1',
      name: 'Servicios de consultoría informática',
      quantity: '10',
      unitPrice: 10000,
      lineTotal: 100000,
      sortOrder: 0,
      vatRateBp: 2100,
      vatCategory: 'S',
      unitCode: 'HUR',
    },
  ],
  discounts: [],
  createdAt: '2026-09-04T09:00:00.000Z',
  updatedAt: '2026-09-04T09:00:00.000Z',
};
