import type { ClassicLabels } from './index';

export const bg: ClassicLabels = {
  companyIdLabel: 'ЕИК',
  recipientTitle: 'Получател:',
  vatNumberPrefix: 'ДДС №: ',
  molPrefix: 'МОЛ: ',
  issuedAtPrefix: 'Дата на издаване: ',
  taxEventPrefix: 'Данъчно събитие: ',
  validUntilPrefix: () => 'Валидно до: ',
  deliveryDatePrefix: 'Дата на доставка: ',
  transportReasonPrefix: 'Основание за транспорта: ',
  transportedAtPrefix: 'Дата и час на транспорта: ',
  carrierNamePrefix: 'Превозвач: ',
  transportNotePrefix: 'Данни за транспорта: ',
  statusPaid: () => 'Статус: ПЛАТЕНО',
  statusCancelled: () => 'Статус: АНУЛИРАНА',
  phonePrefix: 'Телефон: ',
  bicPrefix: 'BIC: ',
  preparedByPrefix: () => 'Съставил: ',
  recipientSignaturePrefix: () => 'Получател: ',
  colName: 'Наименование',
  colQuantity: 'Количество',
  colPrice: 'Цена',
  colTotal: 'Общо',
  vatBasePrefix: 'Данъчна основа:',
  vatRatePrefix: (percent) => `ДДС (${percent}%):`,
  subtotalLabel: 'Междинна сума:',
  discountRowLabel: (percent, customLabel) =>
    `Отстъпка${percent !== null ? ` (${percent}%)` : ''}${customLabel ? ` – ${customLabel}` : ''}:`,
  totalLabel: 'Общо:',
  dueLabel: 'Сума за плащане:',
  exemptionPrefix: 'Основание за неначисляване на ДДС: ',
  originalMarker: ' (Оригинал)',
  draftLabel: 'Чернова',
  correctsInvoice: (number, date) => `Към фактура № ${number} от ${date}`,
  documentType: {
    invoice: 'Фактура',
    proforma: 'Проформа фактура',
    credit_note: 'Кредитно известие',
    debit_note: 'Дебитно известие',
    quote: 'Ценова оферта',
    delivery_note: 'Стокова разписка',
  },
  watermarkMain: 'ЧЕРНОВА',
  watermarkSub: 'БЕЗ ПРАВНА СИЛА',
};
