import type { ClassicLabels } from './index';

export const de: ClassicLabels = {
  companyIdLabel: 'Handelsregisternummer',
  recipientTitle: 'Rechnungsempfänger:',
  vatNumberPrefix: 'USt-IdNr.: ',
  molPrefix: 'Vertreten durch: ',
  issuedAtPrefix: 'Rechnungsdatum: ',
  taxEventPrefix: 'Leistungsdatum: ',
  validUntilPrefix: 'Gültig bis: ',
  statusPaid: 'Status: BEZAHLT',
  statusCancelled: 'Status: STORNIERT',
  phonePrefix: 'Telefon: ',
  bicPrefix: 'BIC: ',
  preparedByPrefix: 'Erstellt von: ',
  recipientSignaturePrefix: 'Empfangen von: ',
  colName: 'Bezeichnung',
  colQuantity: 'Menge',
  colPrice: 'Preis',
  colTotal: 'Gesamt',
  vatBasePrefix: 'Nettobetrag:',
  vatRatePrefix: (percent) => `USt. (${percent}%):`,
  subtotalLabel: 'Zwischensumme:',
  discountRowLabel: (percent, customLabel) =>
    `Rabatt${percent !== null ? ` (${percent}%)` : ''}${customLabel ? ` – ${customLabel}` : ''}:`,
  totalLabel: 'Gesamtbetrag:',
  dueLabel: 'Zu zahlender Betrag:',
  exemptionPrefix: 'Hinweis: ',
  originalMarker: '',
  draftLabel: 'Entwurf',
  documentType: {
    invoice: 'Rechnung',
    proforma: 'Proforma-Rechnung',
    credit_note: 'Rechnungskorrektur',
    debit_note: 'Belastungsanzeige',
    quote: 'Angebot',
  },
  watermarkMain: 'ENTWURF',
  watermarkSub: 'RECHTLICH NICHT GÜLTIG',
};
