import type { ClassicLabels } from './index';

export const en: ClassicLabels = {
  companyIdLabel: 'Company registration no.',
  supplierTitle: 'Supplier:',
  recipientTitle: () => 'Recipient:',
  vatNumberPrefix: 'VAT no.: ',
  molPrefix: 'Representative: ',
  issuedAtPrefix: () => 'Issue date: ',
  taxEventPrefix: 'Date of supply: ',
  validUntilPrefix: () => 'Valid until: ',
  deliveryDatePrefix: 'Delivery date: ',
  transportReasonPrefix: 'Transport reason: ',
  transportedAtPrefix: 'Transport date and time: ',
  carrierNamePrefix: 'Carrier: ',
  transportNotePrefix: 'Transport details: ',
  statusPaid: () => 'Status: PAID',
  statusCancelled: () => 'Status: CANCELLED',
  phonePrefix: 'Phone: ',
  bicPrefix: 'BIC: ',
  preparedByPrefix: () => 'Prepared by: ',
  recipientSignaturePrefix: () => 'Received by: ',
  colName: 'Description',
  colQuantity: 'Quantity',
  colUnit: 'Unit',
  colVatRate: 'VAT rate',
  colPrice: 'Price',
  colTotal: 'Total',
  unitLabels: {
    C62: 'unit',
    H87: 'pc',
    HUR: 'h',
    DAY: 'day',
    MON: 'mo',
    KGM: 'kg',
    MTR: 'm',
    MTK: 'm²',
    LTR: 'l',
    KMT: 'km',
    SET: 'set',
  },
  reverseChargeLineMarker: '—',
  vatBasePrefix: 'Net amount (excl. VAT):',
  vatRatePrefix: (percent) => `VAT (${percent}%):`,
  subtotalLabel: 'Subtotal:',
  discountRowLabel: (percent, customLabel) =>
    `Discount${percent !== null ? ` (${percent}%)` : ''}${customLabel ? ` – ${customLabel}` : ''}:`,
  totalLabel: 'Total:',
  totalWithVatLabel: 'Total (incl. VAT):',
  netValueLabel: 'Total value:',
  dueLabel: 'Amount due:',
  creditDueLabel: 'Total credited:',
  paidLabel: 'Amount paid:',
  exemptionPrefix: 'VAT exemption ground: ',
  operationNaturePrefix: 'Nature of operation: ',
  operationNatureLabels: {
    goods: 'Goods delivery',
    services: 'Service provision',
    mixed: 'Goods delivery and service provision',
  },
  deliveryAddressPrefix: 'Delivery address: ',
  vatAmountLocalLine: ({ currencyLabel, amount, sourceLabel, rate, date, table }) =>
    `VAT amount in ${currencyLabel}: ${amount} (${sourceLabel} rate ${rate} of ${date}${table ? `, table No. ${table}` : ''})`,
  proformaNotice: 'This is not a VAT invoice.',
  reverseChargeNote: 'Reverse charge – Article 196 of Council Directive 2006/112/EC',
  originalMarker: ' (Original)',
  draftLabel: 'Draft',
  numberSign: 'no.',
  draftTitle: (l) => `${l} (draft)`,
  correctsInvoice: (number, date) => `Relates to invoice no. ${number} of ${date}`,
  correctionReasonPrefix: 'Reason: ',
  documentType: {
    invoice: 'Invoice',
    proforma: 'Pro forma invoice',
    credit_note: 'Credit note',
    debit_note: 'Debit note',
    quote: 'Quote',
    delivery_note: 'Delivery note',
  },
  watermarkMain: 'DRAFT',
  watermarkSub: 'NOT LEGALLY VALID',
  vatBaseWithRatePrefix: (percent) => `Net amount at ${percent}%:`,
  buyerReferencePrefix: 'Your reference: ',
  paymentTermsPrefix: 'Payment terms: ',
  correctionKsefNumberPrefix: 'KSeF number of the corrected invoice: ',
  taxEventDuzpPrefix: 'Date of taxable supply (DUZP): ',
  paymentTermsDaysText: (days) => (days === 0 ? 'on receipt' : `${days} days`),
  companyRegisterLabel: 'Register entry',
  dueDatePrefix: 'Due date: ',
};
