import type { ClassicLabels } from './index';

export const en: ClassicLabels = {
  companyIdLabel: 'Company registration no.',
  recipientTitle: 'Recipient:',
  vatNumberPrefix: 'VAT no.: ',
  molPrefix: 'Representative: ',
  issuedAtPrefix: 'Issue date: ',
  taxEventPrefix: 'Tax event: ',
  validUntilPrefix: () => 'Valid until: ',
  deliveryDatePrefix: 'Delivery date: ',
  transportReasonPrefix: 'Transport reason: ',
  transportedAtPrefix: 'Transport date and time: ',
  carrierNamePrefix: 'Carrier: ',
  transportNotePrefix: 'Transport details: ',
  statusPaid: () => 'Status: PAID',
  statusCancelled: () => 'Status: CANCELLED',
  phonePrefix: 'Phone: ',
  bicPrefix: 'BIC: ',
  preparedByPrefix: () => 'Prepared by: ',
  recipientSignaturePrefix: () => 'Received by: ',
  colName: 'Description',
  colQuantity: 'Quantity',
  colPrice: 'Price',
  colTotal: 'Total',
  vatBasePrefix: 'Taxable amount:',
  vatRatePrefix: (percent) => `VAT (${percent}%):`,
  subtotalLabel: 'Subtotal:',
  discountRowLabel: (percent, customLabel) =>
    `Discount${percent !== null ? ` (${percent}%)` : ''}${customLabel ? ` – ${customLabel}` : ''}:`,
  totalLabel: 'Total:',
  dueLabel: 'Amount due:',
  exemptionPrefix: 'VAT exemption ground: ',
  originalMarker: ' (Original)',
  draftLabel: 'Draft',
  correctsInvoice: (number, date) => `Relates to invoice no. ${number} of ${date}`,
  documentType: {
    invoice: 'Invoice',
    proforma: 'Proforma invoice',
    credit_note: 'Credit note',
    debit_note: 'Debit note',
    quote: 'Quote',
    delivery_note: 'Delivery note',
  },
  watermarkMain: 'DRAFT',
  watermarkSub: 'NOT LEGALLY VALID',
};
