import type { ClassicLabels } from './index';

export const es: ClassicLabels = {
  companyIdLabel: 'NIF',
  recipientTitle: 'Cliente:',
  vatNumberPrefix: 'NIF-IVA: ',
  molPrefix: 'Representante: ',
  issuedAtPrefix: 'Fecha de expedición: ',
  taxEventPrefix: 'Fecha de la operación: ',
  validUntilPrefix: 'Válido hasta: ',
  deliveryDatePrefix: 'Fecha de entrega: ',
  transportReasonPrefix: 'Motivo del transporte: ',
  transportedAtPrefix: 'Fecha y hora del transporte: ',
  carrierNamePrefix: 'Transportista: ',
  transportNotePrefix: 'Detalles del transporte: ',
  statusPaid: 'Estado: PAGADA',
  statusCancelled: 'Estado: ANULADA',
  phonePrefix: 'Teléfono: ',
  bicPrefix: 'BIC: ',
  preparedByPrefix: 'Emitido por: ',
  recipientSignaturePrefix: 'Recibí: ',
  colName: 'Descripción',
  colQuantity: 'Cantidad',
  colPrice: 'Precio',
  colTotal: 'Total',
  vatBasePrefix: 'Base imponible:',
  vatRatePrefix: (percent) => `IVA (${percent}%):`,
  subtotalLabel: 'Subtotal:',
  discountRowLabel: (percent, customLabel) =>
    `Descuento${percent !== null ? ` (${percent}%)` : ''}${customLabel ? ` – ${customLabel}` : ''}:`,
  totalLabel: 'Total:',
  dueLabel: 'Total a pagar:',
  exemptionPrefix: 'Operación exenta de IVA según el ',
  originalMarker: ' (Original)',
  draftLabel: 'Borrador',
  documentType: {
    invoice: 'Factura',
    proforma: 'Factura proforma',
    credit_note: 'Factura rectificativa (abono)',
    debit_note: 'Factura rectificativa (cargo)',
    quote: 'Presupuesto',
    delivery_note: 'Albarán',
  },
  watermarkMain: 'BORRADOR',
  watermarkSub: 'SIN VALIDEZ LEGAL',
};
