import type { ClassicLabels } from './index';

export const fr: ClassicLabels = {
  companyIdLabel: 'SIREN',
  recipientTitle: 'Client :',
  vatNumberPrefix: 'N° TVA intracommunautaire : ',
  molPrefix: 'Représentant légal : ',
  issuedAtPrefix: "Date d'émission : ",
  taxEventPrefix: 'Date de livraison / prestation : ',
  validUntilPrefix: "Valable jusqu'au : ",
  statusPaid: 'Statut : PAYÉE',
  statusCancelled: 'Statut : ANNULÉE',
  phonePrefix: 'Téléphone : ',
  bicPrefix: 'BIC : ',
  preparedByPrefix: 'Établi par : ',
  recipientSignaturePrefix: 'Reçu par : ',
  colName: 'Désignation',
  colQuantity: 'Quantité',
  colPrice: 'Prix unitaire',
  colTotal: 'Total',
  vatBasePrefix: 'Base HT :',
  vatRatePrefix: (percent) => `TVA (${String(percent).replace('.', ',')}%) :`,
  subtotalLabel: 'Sous-total :',
  discountRowLabel: (percent, customLabel) =>
    `Remise${percent !== null ? ` (${String(percent).replace('.', ',')}%)` : ''}${customLabel ? ` – ${customLabel}` : ''} :`,
  totalLabel: 'Total :',
  dueLabel: 'Net à payer :',
  exemptionPrefix: "Motif d'exonération de TVA : ",
  originalMarker: ' (Original)',
  draftLabel: 'Brouillon',
  documentType: {
    invoice: 'Facture',
    proforma: 'Facture pro forma',
    credit_note: 'Avoir',
    debit_note: 'Note de débit',
    quote: 'Devis',
  },
  watermarkMain: 'BROUILLON',
  watermarkSub: 'SANS VALEUR LÉGALE',
};
