import type { ClassicLabels } from './index';

export const it: ClassicLabels = {
  companyIdLabel: 'Codice fiscale',
  recipientTitle: 'Destinatario:',
  vatNumberPrefix: 'P. IVA: ',
  molPrefix: 'Rappresentante: ',
  issuedAtPrefix: 'Data di emissione: ',
  taxEventPrefix: 'Data di effettuazione: ',
  validUntilPrefix: 'Valida fino al: ',
  deliveryDatePrefix: 'Data di consegna: ',
  transportReasonPrefix: 'Causale del trasporto: ',
  transportedAtPrefix: 'Data e ora di inizio del trasporto: ',
  carrierNamePrefix: 'Vettore: ',
  transportNotePrefix: 'Dati del trasporto: ',
  statusPaid: 'Stato: PAGATA',
  statusCancelled: 'Stato: ANNULLATA',
  phonePrefix: 'Tel.: ',
  bicPrefix: 'BIC: ',
  preparedByPrefix: 'Emessa da: ',
  recipientSignaturePrefix: 'Ricevuta da: ',
  colName: 'Descrizione',
  colQuantity: 'Quantità',
  colPrice: 'Prezzo',
  colTotal: 'Totale',
  vatBasePrefix: 'Imponibile:',
  vatRatePrefix: (percent) => `IVA (${percent}%):`,
  subtotalLabel: 'Subtotale:',
  discountRowLabel: (percent, customLabel) =>
    `Sconto${percent !== null ? ` (${percent}%)` : ''}${customLabel ? ` – ${customLabel}` : ''}:`,
  totalLabel: 'Totale:',
  dueLabel: 'Totale da pagare:',
  exemptionPrefix: "Natura dell'operazione: ",
  originalMarker: ' (Originale)',
  draftLabel: 'Bozza',
  documentType: {
    invoice: 'Fattura',
    proforma: 'Fattura proforma',
    credit_note: 'Nota di credito',
    debit_note: 'Nota di debito',
    quote: 'Preventivo',
    delivery_note: 'Documento di trasporto (DDT)',
  },
  watermarkMain: 'BOZZA',
  watermarkSub: 'DOCUMENTO NON VALIDO AI FINI FISCALI',
};
