import type { DocumentType } from '@fakturcho/shared-types';
import type { ClassicLabels } from './index';

// Every document noun is feminine (fattura, nota di credito/debito) except
// "il preventivo" and "il documento di trasporto".
const IT_MASCULINE_TYPES = new Set<DocumentType>(['quote', 'delivery_note']);
const agree = (documentType: DocumentType, feminine: string, masculine: string) =>
  IT_MASCULINE_TYPES.has(documentType) ? masculine : feminine;

export const it: ClassicLabels = {
  companyIdLabel: 'Codice fiscale',
  supplierTitle: 'Cedente/prestatore:',
  recipientTitle: () => 'Destinatario:',
  vatNumberPrefix: 'P. IVA: ',
  molPrefix: 'Rappresentante: ',
  issuedAtPrefix: () => 'Data di emissione: ',
  taxEventPrefix: 'Data di effettuazione: ',
  validUntilPrefix: (documentType) => agree(documentType, 'Valida fino al: ', 'Valido fino al: '),
  deliveryDatePrefix: 'Data di consegna: ',
  transportReasonPrefix: 'Causale del trasporto: ',
  transportedAtPrefix: 'Data e ora di inizio del trasporto: ',
  carrierNamePrefix: 'Vettore: ',
  transportNotePrefix: 'Dati del trasporto: ',
  statusPaid: (documentType) => agree(documentType, 'Stato: PAGATA', 'Stato: PAGATO'),
  statusCancelled: (documentType) => agree(documentType, 'Stato: ANNULLATA', 'Stato: ANNULLATO'),
  phonePrefix: 'Tel.: ',
  bicPrefix: 'BIC: ',
  preparedByPrefix: (documentType) => agree(documentType, 'Emessa da: ', 'Emesso da: '),
  recipientSignaturePrefix: (documentType) => agree(documentType, 'Ricevuta da: ', 'Ricevuto da: '),
  colName: 'Descrizione',
  colQuantity: 'Quantità',
  colUnit: 'Unità di misura',
  colVatRate: 'Aliquota IVA',
  colPrice: 'Prezzo',
  colTotal: 'Totale',
  unitLabels: {
    C62: 'pz',
    H87: 'pz',
    HUR: 'h',
    DAY: 'gg',
    MON: 'mese',
    KGM: 'kg',
    MTR: 'm',
    MTK: 'm²',
    LTR: 'l',
    KMT: 'km',
    SET: 'set',
  },
  reverseChargeLineMarker: '—',
  vatBasePrefix: 'Imponibile:',
  vatRatePrefix: (percent) => `IVA (${percent}%):`,
  subtotalLabel: 'Subtotale:',
  discountRowLabel: (percent, customLabel) =>
    `Sconto${percent !== null ? ` (${percent}%)` : ''}${customLabel ? ` – ${customLabel}` : ''}:`,
  totalLabel: 'Totale:',
  netValueLabel: 'Valore totale:',
  dueLabel: 'Totale da pagare:',
  creditDueLabel: 'Totale a credito:',
  paidLabel: 'Importo pagato:',
  exemptionPrefix: 'Natura dell’operazione: ',
  operationNaturePrefix: 'Natura dell’operazione (Francia): ',
  operationNatureLabels: {
    goods: 'Cessione di beni',
    services: 'Prestazione di servizi',
    mixed: 'Cessione di beni e prestazione di servizi',
  },
  deliveryAddressPrefix: 'Indirizzo di consegna: ',
  vatAmountLocalLine: ({ currencyLabel, amount, sourceLabel, rate, date, table }) =>
    `Importo IVA in ${currencyLabel}: ${amount} (tasso ${sourceLabel} ${rate} del ${date}${table ? `, tabella n. ${table}` : ''})`,
  proformaNotice:
    'Documento privo di valenza fiscale ai sensi dell’art. 21 D.P.R. 633/1972; la fattura sarà emessa al pagamento.',
  reverseChargeNote: 'Inversione contabile – art. 196 della direttiva 2006/112/CE',
  originalMarker: ' (Originale)',
  draftLabel: 'Bozza',
  numberSign: 'n.',
  draftTitle: (l) => `Bozza di ${l.charAt(0).toLowerCase()}${l.slice(1)}`,
  correctsInvoice: (number, date) => `Riferita alla fattura n. ${number} del ${date}`,
  correctionReasonPrefix: 'Causale: ',
  documentType: {
    invoice: 'Fattura',
    proforma: 'Fattura proforma',
    credit_note: 'Nota di credito',
    debit_note: 'Nota di debito',
    quote: 'Preventivo',
    delivery_note: 'Documento di trasporto (DDT)',
  },
  watermarkMain: 'BOZZA',
  watermarkSub: 'DOCUMENTO NON VALIDO AI FINI FISCALI',
  vatBaseWithRatePrefix: (percent) => `Imponibile (${percent}%):`,
  buyerReferencePrefix: 'Vostro riferimento: ',
  paymentTermsPrefix: 'Termini di pagamento: ',
  foreignVatNumberPrefix: 'Numero identificativo IVA: ',
  correctionKsefNumberPrefix: 'Numero KSeF della fattura corretta: ',
  paymentTermsDaysText: (days) => (days === 0 ? 'alla ricezione' : `${days} giorni`),
};
