import type { ClassicLabels } from './index';

export const pl: ClassicLabels = {
  companyIdLabel: 'NIP',
  recipientTitle: 'Nabywca:',
  vatNumberPrefix: 'NIP UE: ',
  molPrefix: 'Reprezentant: ',
  issuedAtPrefix: 'Data wystawienia: ',
  taxEventPrefix: 'Data sprzedaży: ',
  validUntilPrefix: 'Ważna do: ',
  statusPaid: 'Status: ZAPŁACONO',
  statusCancelled: 'Status: ANULOWANA',
  phonePrefix: 'Telefon: ',
  bicPrefix: 'BIC: ',
  preparedByPrefix: 'Wystawił: ',
  recipientSignaturePrefix: 'Odebrał: ',
  colName: 'Nazwa',
  colQuantity: 'Ilość',
  colPrice: 'Cena',
  colTotal: 'Wartość',
  vatBasePrefix: 'Wartość netto:',
  vatRatePrefix: (percent) => `VAT (${percent}%):`,
  subtotalLabel: 'Suma częściowa:',
  discountRowLabel: (percent, customLabel) =>
    `Rabat${percent !== null ? ` (${percent}%)` : ''}${customLabel ? ` – ${customLabel}` : ''}:`,
  totalLabel: 'Razem:',
  dueLabel: 'Do zapłaty:',
  exemptionPrefix: 'Podstawa zwolnienia: ',
  originalMarker: '',
  draftLabel: 'Wersja robocza',
  documentType: {
    invoice: 'Faktura',
    proforma: 'Faktura pro forma',
    credit_note: 'Faktura korygująca',
    debit_note: 'Nota debetowa',
    quote: 'Oferta',
  },
  watermarkMain: 'WERSJA ROBOCZA',
  watermarkSub: 'DOKUMENT BEZ MOCY PRAWNEJ',
};
