import type { ClassicLabels } from './index';

export const ro: ClassicLabels = {
  companyIdLabel: 'CUI',
  recipientTitle: 'Cumpărător:',
  vatNumberPrefix: 'Cod TVA: ',
  molPrefix: 'Reprezentant legal: ',
  issuedAtPrefix: 'Data emiterii: ',
  taxEventPrefix: 'Data livrării/prestării: ',
  validUntilPrefix: 'Valabilă până la: ',
  deliveryDatePrefix: 'Data livrării: ',
  transportReasonPrefix: 'Scopul transportului: ',
  transportedAtPrefix: 'Data și ora transportului: ',
  carrierNamePrefix: 'Transportator: ',
  transportNotePrefix: 'Detalii transport: ',
  statusPaid: 'Status: PLĂTITĂ',
  statusCancelled: 'Status: ANULATĂ',
  phonePrefix: 'Telefon: ',
  bicPrefix: 'BIC: ',
  preparedByPrefix: 'Întocmit de: ',
  recipientSignaturePrefix: 'Semnătură de primire: ',
  colName: 'Denumire produse sau servicii',
  colQuantity: 'Cantitate',
  colPrice: 'Preț unitar',
  colTotal: 'Valoare',
  vatBasePrefix: 'Bază impozabilă:',
  vatRatePrefix: (percent) => `TVA (${percent}%):`,
  subtotalLabel: 'Subtotal:',
  discountRowLabel: (percent, customLabel) =>
    `Reducere${percent !== null ? ` (${percent}%)` : ''}${customLabel ? ` – ${customLabel}` : ''}:`,
  totalLabel: 'Total:',
  dueLabel: 'Total de plată:',
  exemptionPrefix: '',
  originalMarker: ' (Original)',
  draftLabel: 'Ciornă',
  documentType: {
    invoice: 'Factură',
    proforma: 'Factură proformă',
    credit_note: 'Notă de credit',
    debit_note: 'Notă de debit',
    quote: 'Ofertă',
    delivery_note: 'Aviz de însoțire a mărfii',
  },
  watermarkMain: 'CIORNĂ',
  watermarkSub: 'FĂRĂ VALOARE LEGALĂ',
};
