import type { DocumentDto } from '@fakturcho/shared-types';

export const deDomesticB2GInvoice: DocumentDto = {
  id: 'doc-de-b2g-1',
  documentType: 'invoice',
  status: 'sent',
  number: 11,
  numberPrefix: null,
  numberSuffix: null,
  referenceNumber: null,
  originalDocumentId: null,
  issuedAt: '2026-09-05',
  taxEventAt: '2026-09-05',
  dueAt: '2026-09-19',
  validUntil: null,
  deliveryDate: '2026-09-05',
  buyerReference: null,
  paymentMeansCode: '58',
  paymentTermsNote: 'Zahlbar innerhalb von 30 Tagen',
  subtotal: 300000,
  discountTotal: 0,
  amount: 357000,
  vatIncluded: false,
  vatRateBp: 1900,
  vatAmount: 57000,
  vatExemptionGround: null,
  currency: 'EUR',
  clientId: 'client-4',
  preparedBy: 'Anna Schmidt',
  notes: null,
  emailText: null,
  emailedAt: null,
  templateId: 'classic',
  documentLanguage: 'en',
  issuer: {
    companyName: 'Muster Consulting GmbH',
    eik: 'HRB 123456',
    mol: null,
    addressLine: 'Musterstraße 10, 10115 Berlin',
    street: 'Musterstraße 10',
    postcode: '10115',
    countyRegion: null,
    city: 'Berlin',
    country: 'DE',
    phone: '+49 30 1234567',
    vatRegistered: true,
    vatNumber: 'DE123456789',
    bankName: 'Deutsche Bank AG',
    iban: 'DE89370400440532013000',
    bic: 'COBADEFFXXX',
    altIban: null,
  },
  recipient: {
    companyName: 'Stadtverwaltung Musterstadt',
    eik: null,
    vatNumber: null,
    address: 'Rathausplatz 1, 12345 Musterstadt',
    street: 'Rathausplatz 1',
    postcode: '12345',
    countyRegion: null,
    country: 'DE',
    email: 'rechnungseingang@musterstadt.de',
    mol: null,
    sdiRecipientCode: null,
    pec: null,
  },
  lineItems: [
    {
      id: 'line-1',
      name: 'IT infrastructure consulting',
      quantity: '12',
      unitPrice: 25000,
      lineTotal: 300000,
      sortOrder: 0,
      vatRateBp: 1900,
      vatCategory: 'S',
      unitCode: 'HUR',
    },
  ],
  discounts: [],
  createdAt: '2026-09-05T09:00:00.000Z',
  updatedAt: '2026-09-05T09:00:00.000Z',
};
